
set(target "crazypoppersapp")
set(working_dir "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers")
set(src_and_dest_list
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/BoardView.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/BoardView.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/BottomBar.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/BottomBar.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/BulletDot.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/BulletDot.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/CreatureCell.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/CreatureCell.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/GameLabel.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/GameLabel.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/GameScreen.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/GameScreen.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/HudStat.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/HudStat.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/LevelSelectOverlay.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/LevelSelectOverlay.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/LevelTile.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/LevelTile.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/Main.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/Main.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/OverlayPanel.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/OverlayPanel.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/PauseButton.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/PauseButton.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/PauseOverlay.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/PauseOverlay.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/PopButton.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/PopButton.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/ResultOverlay.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/ResultOverlay.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/Shockwave.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/Shockwave.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/Theme.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/Theme.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/TopBar.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/TopBar.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers/qml/CrazyPoppers/WoodBackground.qml"
    "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/CrazyPoppers/WoodBackground.qml"

)
set(timestamp_file "C:/Users/ashqe/Documents/qt_projects/CrazyPoppers-build/.qt/crazypoppersapp_qml.txt")
